### ISSUE TITLE
Failing to import files with paths that contain upper-case characters on systems with case-sensitive filenames (i.e. GNU/Linux)

### ISSUE THREAD

**Issue by NominoX** [juhu1705/CaRP#9]
**Describe the bug**
Failing to import files with paths that contain upper-case characters on systems with case-sensitive filenames (i.e. GNU/Linux).
There is no visible error in the GUI, however exception info is output to stderr (see "Log" section).

**To Reproduce**
Steps to reproduce the behavior (GNU/Linux):
1. Go to 'In-Out-Settings'
2. Drag-and-Drop a file with a path containing upper-case letters into the "Input File" box (or use the search button)

**Log**
```
[00:00:00] [SEVERE] [Thread-8:ExcelImporter:getInput] [Wahlverteiler] 
java.io.FileNotFoundException: /home/user/downloads/carp.xlsx (Datei oder Verzeichnis nicht gefunden)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at de.juhu.dateimanager.ExcelImporter.getInput(ExcelImporter.java:246)
    at de.juhu.dateimanager.ExcelImporter.readXLSXImproved(ExcelImporter.java:191)
    at de.juhu.distributor.Distributor.importFile(Distributor.java:1079)
    at de.juhu.distributor.Distributor.readFile(Distributor.java:1044)
    at de.juhu.distributor.Distributor.<init>(Distributor.java:170)
    at de.juhu.guiFX.GUIManager.lambda$onDragDroppedInput$0(GUIManager.java:646)
    at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-8" java.lang.NullPointerException
        at org.apache.poi.poifs.filesystem.FileMagic.prepareToCheckMagic(FileMagic.java:184)
        at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:174)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:301)
        at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:37)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:303)
        at de.juhu.dateimanager.ExcelImporter.readXLSXImproved(ExcelImporter.java:195)
        at de.juhu.distributor.Distributor.importFile(Distributor.java:1079)
        at de.juhu.distributor.Distributor.readFile(Distributor.java:1044)
        at de.juhu.distributor.Distributor.<init>(Distributor.java:170)
        at de.juhu.guiFX.GUIManager.lambda$onDragDroppedInput$0(GUIManager.java:646)
        at java.lang.Thread.run(Thread.java:748)
```

**Desktop (please complete the following information):**
 - OS: GNU/Linux

**Additional context**
The cause of the problem is that the input path unnecessarily gets converted to lower-case in the Distributor's `importFile(String)` method:
https://github.com/juhu1705/CaRP/blob/306bbe9e9899479f499a5f26033523e0c8e8ce57/CaRP/src/de/juhu/distributor/Distributor.java#L1095
This works fine for systems where the lower-case path always represents the same file as the original path (although not even that can be guranteed), but obviously results in a "file not found" error on systems with case-sensitive paths, i.e. Linux.

**Comment by juhu1705** [comment]
I will fix this error as soon as possible

**Comment by juhu1705** [comment]
Fixed
